type SciencesList = {
  [key: string]: string[] | null
}

export const allSciences: SciencesList = {
  Administracja: null,
  'Analityka Medyczna': null,
  'Antropologia i Etnologia': null,
  Archeologia: null,
  'Astronomia i Astrofizyka': null,
  'Automatyka i Robotyka': null,
  Biochemia: null,
  Biofizyka: null,
  Bioinformatyka: null,
  Biologia: null,
  Biotechnologia: null,
  Budownictwo: null,
  Chemia: null,
  Dietetyka: null,
  Dziennikarstwo: null,
  Ekonomia: null,
  Ekonometria: null,
  Elektronika: null,
  Elektromobilność: null,
  Elektrotechnika: null,
  Energetyka: null,
  Europeistyka: null,
  Farmakologia: null,
  // 'Filologia (nie Polska)': null,
  Filozofia: null,
  Finanse: null,
  Fizyka: null,
  'Geodezja i Kartografia': null,
  Geografia: null,
  Geologia: null,
  Górnictwo: null,
  Historia: null,
  'Historia Sztuki': null,
  Informatyka: null,
  'Inżynieria Biomedyczna': null,
  'Inżynieria Materiałowa': null,
  'Inżynieria Metali': null,
  'Inżynieria Naftowa i Gazownictwo': null,
  'Inżynieria Środowiska': null,

  Kognitywistka: null,
  Kulturoznawstwo: null,
  Lingwistyka: null,
  'Lotnictwo i Kosmonautyka': null,
  Matematyka: null,
  'Mechanika i Budowa_Maszyn': null,
  Mechatronika: null,
  Medycyna: null,
  'Obronność i Bezpieczeństwo Narodowe': null,
  'Ochrona Środowiska': null,
  Pedagogika: null,
  Politologia: null,
  Polonistyka: null,
  Prawo: null,
  Psychologia: null,
  Rachunkowość: null,
  Religioznawstwo: null,
  Socjologia: null,
  'Stosunki Międzynarodowe': null,
  Telekomunikacja: null,
  Zarządzanie: null,
}
