import Examples from './logic'
import config from '../../config/config'

export const mainExamples = [
  Examples.Mathematics,
  Examples.Physics,
  Examples.Electronics,
  Examples.Informatics,
  Examples.Mechatronics,
  Examples.Economics,
  Examples.Chemistry,
  Examples.Biophysics,
  Examples.Telecommunications,
  Examples.Astrophysics,
  Examples.PhysicsNanostr,
  Examples.PhysicsNuclear,
  Examples.QuantumEngineering,
]

export const allExamples = [
  // Examples.Administration,
  Examples.MedicalAnalytics,
  Examples.Anthropology,
  Examples.Archeology,
  Examples.Architecture,
  Examples.Astrophysics,
  Examples.AutomaticsRobotics,
  Examples.Biochemistry,
  Examples.Biophysics,
  Examples.Bioeconomy,
  Examples.Biology,
  Examples.Biotechnology,
  Examples.CivilEngineering,
  Examples.Chemistry,
  Examples.Dietetics,
  Examples.Journalism,
  Examples.Economics,
  Examples.Econometrics,
  Examples.Electromobility,
  Examples.Electronics,
  Examples.ElectricalEng,
  Examples.Energetics,
  Examples.EuropeanStudies,
  Examples.Pharmacology,
  Examples.Philosophy,
  Examples.Finances,
  // PHYSICS
  Examples.Physics,
  Examples.PhysicsNanostr,
  Examples.PhysicsNuclear,
  Examples.QuantumEngineering,
  //
  Examples.Cartography,
  Examples.Geography,
  Examples.Geology,
  Examples.Mining,
  Examples.History,
  Examples.HistoryOfArt,
  Examples.Informatics,
  Examples.BiomedicalEng,
  Examples.MaterialEng,
  Examples.MetalEng,
  Examples.GasEng,
  Examples.EnvironmentalEng,
  Examples.CognitiveScience,
  Examples.CulturalStudies,
  Examples.Linguistics,
  Examples.Cosmonautics,
  Examples.Mathematics,
  Examples.Mechanics,
  Examples.Mechatronics,
  Examples.Medicine,
  Examples.DefenseStudies,
  Examples.Ecology,
  Examples.Politology,
  Examples.Law,
  Examples.Psychology,
  Examples.Accountancy,
  Examples.ReligiousStudies,
  Examples.Sociology,
  Examples.InternationalStudies,
  Examples.Telecommunications,
  Examples.Transport,
  Examples.ManagementScience,
].filter((e) => (config.production ? e(1).color != '#111' : e))
